### ISSUE TITLE
Choose country

### ISSUE THREAD

**Issue by 89z** [ryanhaticus/superiorproxy.com#1]
You should be able to choose the country, even with the free option.

In my case, I need GB, so if I am not able to test on the free proxy, then I wont buy the paid version either.

**Comment by ryanhaticus** [comment]
Since proxies actively rotate, we can't guarantee any one country will always be available. Therefore, we don't have the option for this. If you're inclined to the use the API, you can always implement your own logic on your end.

I apologize for the inconvenience.
As always, the paid version is *very* cheap and might be worthy a try. We give full refunds for unsatisfied customers within 72 hours of purchase.

**Comment by 89z** [comment]
I dont understand this:

> Our service scrapes the internet for active proxies and then uploads them here, automagically! 

If you have a paid service, why does the free offer get random proxies from around the internet? Wouldnt it be better to just use the proxies from the paid version, but throttled or something?
